# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_designer_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsformdefinition',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='form_designer_form_cmsformdefinition', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
